# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientOnlyPhone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
