# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamm', '0003_auto_20180412_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verifycode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
