# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mamm', '0004_patient_verifycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
