# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamm', '0006_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientOnlyPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, max_length=50)),
                ('chujonservice', models.BooleanField(default=False)),
                ('huijonservice', models.BooleanField(default=False)),
                ('jiuyiservice', models.BooleanField(default=False)),
                ('verifycode', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
